// <auto-generated />
using CCM_Website.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCM_Website.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241119212210_InitalSetup")]
    partial class InitalSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CCM_Website.Models.Activities", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("CCM_Website.Models.GraduateAttribute", b =>
                {
                    b.Property<int>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeId"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttributeId");

                    b.ToTable("GraduateAttributes");
                });

            modelBuilder.Entity("CCM_Website.Models.LearningPlatform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"));

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkbookId")
                        .HasColumnType("int");

                    b.HasKey("PlatformId");

                    b.ToTable("LearningPlatforms");
                });

            modelBuilder.Entity("CCM_Website.Models.LearningPlatformActivities", b =>
                {
                    b.Property<int>("LearningPlatformId")
                        .HasColumnType("int");

                    b.Property<int>("ActivitiesId")
                        .HasColumnType("int");

                    b.HasKey("LearningPlatformId", "ActivitiesId");

                    b.HasIndex("ActivitiesId");

                    b.ToTable("LearningPlatformActivities");
                });

            modelBuilder.Entity("CCM_Website.Models.Week", b =>
                {
                    b.Property<int>("WeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeekId"));

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<int>("WorkbookId")
                        .HasColumnType("int");

                    b.HasKey("WeekId");

                    b.HasIndex("WorkbookId");

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("CCM_Website.Models.WeekActivities", b =>
                {
                    b.Property<int>("WeekId")
                        .HasColumnType("int");

                    b.Property<int>("ActivitiesId")
                        .HasColumnType("int");

                    b.HasKey("WeekId", "ActivitiesId");

                    b.HasIndex("ActivitiesId");

                    b.ToTable("WeekActivities");
                });

            modelBuilder.Entity("CCM_Website.Models.WeekGraduateAttributes", b =>
                {
                    b.Property<int>("WeekId")
                        .HasColumnType("int");

                    b.Property<int>("GraduateAttributeId")
                        .HasColumnType("int");

                    b.HasKey("WeekId", "GraduateAttributeId");

                    b.HasIndex("GraduateAttributeId");

                    b.ToTable("WeekGraduateAttributes");
                });

            modelBuilder.Entity("CCM_Website.Models.Workbook", b =>
                {
                    b.Property<int>("WorkbookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkbookId"));

                    b.Property<string>("CourseLead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseLength")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LearningPlatformPlatformId")
                        .HasColumnType("int");

                    b.HasKey("WorkbookId");

                    b.HasIndex("LearningPlatformPlatformId");

                    b.ToTable("WorkBooks");
                });

            modelBuilder.Entity("CCM_Website.Models.LearningPlatformActivities", b =>
                {
                    b.HasOne("CCM_Website.Models.Activities", "Activities")
                        .WithMany("LearningPlatformActivities")
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCM_Website.Models.LearningPlatform", "LearningPlatform")
                        .WithMany("LearningPlatformActivities")
                        .HasForeignKey("LearningPlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activities");

                    b.Navigation("LearningPlatform");
                });

            modelBuilder.Entity("CCM_Website.Models.Week", b =>
                {
                    b.HasOne("CCM_Website.Models.Workbook", "Workbook")
                        .WithMany("Weeks")
                        .HasForeignKey("WorkbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workbook");
                });

            modelBuilder.Entity("CCM_Website.Models.WeekActivities", b =>
                {
                    b.HasOne("CCM_Website.Models.Activities", "Activities")
                        .WithMany("WeekActivities")
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCM_Website.Models.Week", "Week")
                        .WithMany("WeekActivities")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activities");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("CCM_Website.Models.WeekGraduateAttributes", b =>
                {
                    b.HasOne("CCM_Website.Models.GraduateAttribute", "GraduateAttribute")
                        .WithMany("WeekGraduateAttributes")
                        .HasForeignKey("GraduateAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCM_Website.Models.Week", "Week")
                        .WithMany("WeekGraduateAttributes")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GraduateAttribute");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("CCM_Website.Models.Workbook", b =>
                {
                    b.HasOne("CCM_Website.Models.LearningPlatform", "LearningPlatform")
                        .WithMany("Workbooks")
                        .HasForeignKey("LearningPlatformPlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningPlatform");
                });

            modelBuilder.Entity("CCM_Website.Models.Activities", b =>
                {
                    b.Navigation("LearningPlatformActivities");

                    b.Navigation("WeekActivities");
                });

            modelBuilder.Entity("CCM_Website.Models.GraduateAttribute", b =>
                {
                    b.Navigation("WeekGraduateAttributes");
                });

            modelBuilder.Entity("CCM_Website.Models.LearningPlatform", b =>
                {
                    b.Navigation("LearningPlatformActivities");

                    b.Navigation("Workbooks");
                });

            modelBuilder.Entity("CCM_Website.Models.Week", b =>
                {
                    b.Navigation("WeekActivities");

                    b.Navigation("WeekGraduateAttributes");
                });

            modelBuilder.Entity("CCM_Website.Models.Workbook", b =>
                {
                    b.Navigation("Weeks");
                });
#pragma warning restore 612, 618
        }
    }
}
